# Use AWS Lambda Python 3.11 runtime as parent image
FROM public.ecr.aws/lambda/python:3.11

# Set working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Copy requirements file
COPY requirements_lambda_min.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_lambda_min.txt

# Copy function code and model
COPY lambda_function.py .
COPY spam_website_p4.bin .

# Set the CMD to your handler
CMD [ "lambda_function.lambda_handler" ]